# Generated by Django 5.0.1 on 2024-02-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mail',
            field=models.EmailField(default='test@gmail.com', max_length=50),
            preserve_default=False,
        ),
    ]
